exclude: [vendor, Rakefile, Gemfile]
title: 'Kod'
tagline: 'İşe yarar kod hileleri'
description: 'Küçük küçük kod parçacıkları biraya geldi.'
version: 0.1.0
markdown: redcarpet
permalink: pretty
highlighter: pygments
paginate: 10
excerpt_separator: <!--more-->
